### ISSUE TITLE
"ValueError: too many values to unpack" when iterating over LevelDict()

### ISSUE THREAD

**Issue by runeksvendsen** [hoffmann/leveldict#1]
Line 23 should be changed from

```
for k, v in self.db.RangeIter(include_value=False):
```

to

```
for k in self.db.RangeIter(include_value=False):
```

or else we get the error `ValueError: too many values to unpack` because `db.RangeIter()` only yields the keys when include_value is set to False.

**Comment by hoffmann** [comment]
Fixed in 62ae71612fa907e39a59d91db3cf1913fc363b6b
